export const gridData = [
  {
    key: 1,
    heading: "Quick Action Saves a Life",
    image: "/assets/a-1920x1080.png",
    rowSpan: "row-span-10",
    rowSpanSamllScreen: "row-span-7",
    para: "When a car accident occurred, our team was on-site within minutes, stabilizing the injured. Our paramedics ensured the patient received critical care during transport. ",
  },
  {
    key: 2,
    heading: "Quick Action Saves a Life",
    image: "/assets/a1-1920x1080.png",
    rowSpan: "row-span-6",
    rowSpanSamllScreen: "row-span-3",
    para: "When a car accident occurred, our team was on-site within minutes, stabilizing the injured. Our paramedics ensured the patient received critical care during transport. ",
  },
  {
    key: 3,
    heading: "Quick Action Saves a Life",
    image: "/assets/a2-1920x1080.png",
    rowSpan: "row-span-4",
    rowSpanSamllScreen: "row-span-3",
    para: "When a car accident occurred, our team was on-site within minutes, stabilizing the injured. Our paramedics ensured the patient received critical care during transport. ",
  },
  {
    key: 4,
    heading: "Quick Action Saves a Life",
    image: "/assets/IMG-20240209-WA0032-1920x1080.png",
    rowSpan: "row-span-6",
    rowSpanSamllScreen: "row-span-4",
    para: "When a car accident occurred, our team was on-site within minutes, stabilizing the injured. Our paramedics ensured the patient received critical care during transport. ",
  },
  {
    key: 5,
    heading: "Quick Action Saves a Life",
    image: "/assets/IMG-20240209-WA0043-1920x1080.png",
    rowSpan: "row-span-4",
    rowSpanSamllScreen: "row-span-3",
    para: "When a car accident occurred, our team was on-site within minutes, stabilizing the injured. Our paramedics ensured the patient received critical care during transport. ",
  },
];
